name: import cv2

on:
  pull_request_review:
    types: [ submitted ]
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ '3.14' ]
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-nvidia-libs
        with:
          version: "535"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: latest

      - name: Install Python for presence_common
        run: uv python install $(cat .python-version)

      - name: uv sync
        run: uv run poe init

      - name: Import OpenCV
        env:
          LD_LIBRARY_PATH: $(readlink -f ./include):$(echo $LD_LIBRARY_PATH)
        run: uv run python -m opencv_issue_28525
